Add "send confirmation" option
lamby/fastmail-enhancement-suite pull request #10
Opened 2016-10-22 17:42 UTC by jlerner

Dangerous keyboard shortcut workaround.

2016-10-22 18:33 UTC, lamby requested changes

2016-10-22 18:33 UTC, lamby commented on js/main.js
> +  $.option('send_confirmation', function () {
I think you are missing the corresponding option on the option page, no?

2016-10-22 19:11 UTC, jlerner commented on js/main.js
> +  $.option('send_confirmation', function () {
Sorry, it was inadvertently excluded from the commit.

2016-10-22 21:30 UTC, lamby requested changes

2016-10-22 21:30 UTC, lamby commented on pages/options.js
> +    , "default": true
Please change the default to ``false``.

2016-10-22 21:40 UTC, merged

2016-10-22 21:40 UTC, lamby commented
Many thanks :)

2016-10-22 21:42 UTC, lamby commented
Published on the app store as ``1.4.0``

2016-10-25 18:42 UTC, jlerner commented
Thanks for this extension in the first place!

On Sat, Oct 22, 2016 at 5:40 PM, Chris Lamb <notifications@github.com>
wrote:

> Many thanks :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lamby/fastmail-enhancement-suite/pull/10#issuecomment-255555654>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABTBvl-n-n9hIDhQslFf9iTKUUmAE5n9ks5q2oLqgaJpZM4Kd69x>
> .
>